# Generated by Django 5.1.3 on 2024-11-19 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
